### ISSUE TITLE
Fix `UnicodeDecodeError`

### ISSUE THREAD

**Issue by github-young** [jwcarr/bibfish#13]
Hello, I found it reported the `UnicodeDecodeError` on Windows 11, Python 3.12, even though my `tex` and `bib` files are already `ASCII`.
```
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 325323
```

It can be easily fixed by adding `encoding="UTF-8"` in each `open()` function in the code as I confirmed using my tex files. Thank you.

**Comment by jwcarr** [comment]
Thanks! This should be fixed in version 0.3.3.
