### ISSUE TITLE
Repeated author year + letter

### ISSUE THREAD

**Issue by davherari-amu** [jwcarr/bibfish#2]
Hi, thank you for the tool. It is very useful for providing clean reference files. 
I've noticed a small problem with references with similar keywords. For example, if I haven warner2019 and warner2019a, the code might only save warner2019a.
Is there any option to avoid this?
Thank you for your attention.

**Comment by jwcarr** [comment]
Hi! Thanks for reporting this. I've released a new version, 0.0.4, which fixes this bug. Please try upgrading using `pip install --upgrade bibfish` and let me know if this does not resolve the issue.

Thanks!

**Comment by davherari-amu** [comment]
Yes, I've just upgraded it. Thank you, it works perfectly.
