### ISSUE TITLE
Fish through more source .bib files

### ISSUE THREAD

**Issue by rbeyer** [jwcarr/bibfish#4]
It would be nice if *bibfish* could accept more than one .bib file to extract entries from.

**Comment by jwcarr** [comment]
Thanks for the suggestion! This sounds relatively straight-forward, although potentially a little awkward. Specifically, how would you pass multiple file names from the command line? Could be a bit awkward if we had to introduce some path separator. Maybe another option could be to pass a directory name, and all `.bib` files in that dir are opened? I'm curious – what kind of workflow do you have that requires this?

**Comment by jwcarr** [comment]
Another issue just occurred to me: What happens if the two (or more) bibtex files are in conflict? E.g. the same citekey in multiple files.

**Comment by rbeyer** [comment]
## Multiple files

Passing multiple file names on the command line is straightforward, since *bibfish* already uses *argparse*.  Fundamentally, you'll be  changing the argument that accepts .bib files by adding `nargs="*"` to *add_argument()* so that it accepts a list and gobbles whatever is there, and then that value is a list instead of a single value (most of the time it will likely be a list of one, but that's fine).

The simplest thing is to re-arrange the command line calling structure to put the .bib file or files at the end.  Right now it looks like this:
```
bibfish [-h] [-v] [--cc CITE_COMMANDS] [-f] [--sdoi] manuscript_file master_bib_file local_bib_file
```
but it could look like this:
```
bibfish [-h] [-v] [--cc CITE_COMMANDS] [-f] [--sdoi] manuscript_file local_bib_file bib_file [bib_file2 bib_file3 ...]
```
This way you can just add more to the end of the command line if you have more than one.


## Workflow

As far as the workflow, goes, rather than keep one gigantic .bib file, I have several.  For example, I have one .bib file with all of my published papers, one with my abstracts, and then one (which is biggest) that has works that I am not an author or co-author on (but that I reference).  Having these two my_papers.bib and my_abstracts.bib makes it easy for me to generate my CV with a minimal command.  That's just one use case, but I'm sure there are others.

## Duplicate Cite keys

You raise a good point about two .bib files having entries with identical citekeys, but a single .bib file can also have duplicated keys (it shouldn't, but it can).  Currently *bibfish* uses the `re.search()` mechanism so if there are duplicates in a single .bib file, it will only "fish out" the first one.  I think there may be two ways to handle it: (1) raise an error if there are duplicates and (2) let the latest-loaded citekey win.  Either could be the default.  In the first case, it notifies the user, and in the second case provides a mechanism for resolution (user orders .bib files on the command line) without the user having to manually de-duplicate the .bib files.

**Comment by jwcarr** [comment]
Great, thanks, you've persuaded me that this is a good feature to have and that the duplicate citekey thing is not a huge problem (on, this, I think I'd go for a warning and let the last loaded entry win). However, rearranging the argument order to accommodate this feature sounds very problematic... For anyone who is already using Bibfish in their pipeline, this change in behavior would cause their master bib file to be overwritten with the contents of the local bib file!! Eeeek... not good! Not to mention the fact that current users would have to update the order of arguments in their scripts. Bibfish is certainly not a big project, but it has been on PyPI for two years, so there are likely to be at least a few users out there. So, changing the order of arguments seems like a nonstarter to me. Even if we could try to put some safeguards in place, it seems WAY too risky.

We could still add `nargs='*'` to the `master_bib_file` argument. In which case, we get:

```
bibfish [-h] [-v] [--cc CITE_COMMANDS] [-f] [--sdoi] manuscript_file [master_bib_file ...] local_bib_file
```

Although having the greedy argument in the middle feels a little inelegant and would preclude us (I think) from ever permitting a variable number of manuscript files using the same mechanism (I can easily imagine a situation where someone has multiple manuscript files and wants to produce a single refs file). (What I mean is... if we use argument gobbling for `master_bib_file`, we can't later use it for `manuscript_file`).

**Comment by rbeyer** [comment]
That's a fine point.

I'd need to do some testing, but I think it is worse than that.  If you made "master_bib_file" `nargs="*"` then I think it is "greedy" and so if you did it like above, `args.local_bib_file` would always be None, because the list in args.master_bib_file would just consume everything.  However, it is worth testing, I may be wrong.

I respect a desire for backwards compatibility.  So another approach is to leave the three position-arguments as-is, but introduced the new "multi-bib-file" capability via a named argument.  So the command line pattern would stay the same (anyone that was using it like before would not have things break), but additional .bib files could be added via a `--bib` argument or something.  And we'd probably throw in some logic such that if they gave just two position arguments, that would be fine, as long as `--bib` had something.
